routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/','IndexController@index');


Route::get('/register', 'RegisterController@index')->name('register.index');

Route::group([
    'prefix' => 'aboutus',
    'as' => 'aboutus.',
], function (){
    Route::get('/', 'AboutUsController@index')->name('index');

});

Route::group([
    'prefix' => 'contactus',
    'as' => 'contactus.',
], function (){
    Route::get('/', 'ContactUsController@index')->name('index');

});
Route::group([
    'prefix' => 'product',
    'as' => 'product.',
], function (){
    Route::get('/{slug}', 'ProductController@index')->name('index');
    Route::post('/store', 'ProductController@store')->name('store');


});
//User dashboard
Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'Dashboard'
], function (){
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::delete('/delete/{id}', 'UserController@destroy')->name('destroy');
});

//Admin dashboard
Route::group([
    'prefix' => 'dashboard',
    'as' => 'dashboard.',
    'namespace' => 'Dashboard'
], function (){
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('/user', 'AdminController@user')->name('user');
    Route::get('/user/edit/{id}', 'AdminController@edit')->name('edit');
    Route::get('/product', 'ProductController@index')->name('product');
    Route::post('/product/store', 'ProductController@store')->name('product.store');
    Route::delete('/product/delete/{id}', 'ProductController@destroy')->name('product.destroy');


    Route::get('/category', 'CategoryController@index')->name('category');
    Route::post('/category/save', 'CategoryController@save')->name('save');
    Route::delete('/category/delete/{id}', 'CategoryController@destroy')->name('category.destroy');
    Route::put('/category/update/{id}', 'CategoryController@update')->name('category.update');


    Route::get('/bidproduct', 'BidProductController@index')->name('bid');





});

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Foundation\Auth\User;

class AdminController extends Controller
{
    //
    public function index(){
        return view('dashboard.user.index');
    }

    public function user(){
        $users = User::orderBy('id', 'desc')->get();
        return view('dashboard.admin.index',compact('users'));
    }

    public function edit(Request $request, $id){
        $user = User::findOrFail($id);
        return view('dashboard.admin.edit', compact('user'));
    }
}

app/Http/Controllers/Dashboard/BidProductController.php
<?php

namespace App\Http\Controllers\Dashboard;


use App\Product;
use App\ProductBid;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class BidProductController extends Controller
{
    //
    public function index(){
        $products = Product::query()->where('user_id',Auth::id())->with([
            'bids' => function($q){
                return $q->orderBy('id','desc')->take(10);
            }
        ])->get();





        return view('dashboard.admin.bidproduct', compact('products'));;
    }

}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;


class CategoryController extends Controller
{
    //
    public function index(){
        $categories = Category::orderBy('id', 'desc')->get();

        return view('dashboard.admin.category',compact('categories'));
    }

    public function save(Request $request){
        $validation =  $request->validate([
            'name' =>'required|unique:categories,name',
            ]);

        Category::create([
            'name' => $request->input('name')
        ]);

        return redirect()->route('dashboard.category')->with('status', 'Category is Added');
    }

    public function destroy($id){
        Category::query()->where('id',$id)->delete();
        return response()->json([
           'success' => true
        ]);
    }

    public function update(Request $request,$id){
        $category = Category::query()->where('id', $id)->firstOrFail();
        $category->name = $request->input('name');
        $category->update();
        return response()->json([
            'success'=> true
        ]);
    }
}

app/Http/Controllers/Dashboard/ProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\Http\Controllers\Controller;
use App\Product;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Validator;

class ProductController extends Controller
{
    public function index(){

        $products = Product::query();

        if(!isAdmin(Auth::user())){
            $products->where('user_id',Auth::id());
        }

        $products = $products->orderBy('id', 'desc')->get();

        $categories = Category::orderBy('id', 'desc')->get();
        return view('dashboard.admin.product' , compact('categories', 'products'));
    }

    public function destroy($id){

        $product = Product::query()->where('id',$id)->first();

        @unlink(public_path('/uploads/'.$product->image));
        $product->delete();

        return response()->json([
            'success' => true
        ]);
    }

    public function store(Request $request){

        $slug = Str::slug($request->input('slug'));

        $validator = Validator::make($request->all(), [
            'title' => 'required|min:5',
            'start_price' => 'required|integer',
            'price' => 'required|integer',
            'category_id' => 'required',
            'slug' => 'required|unique:products,slug',
            'description' => 'required',
            'short_description' => 'required',
            'auction_time' => 'required',
            'image' => 'required',
        ]);

        if ($validator->fails()){
            return response()->json([
                'errors' => $validator->errors()
            ]);
        }

        $imageName = time().'.'.$request['image']->getClientOriginalExtension();
        $request['image']->move(public_path('/uploads'), $imageName);

        $product = Product::create([
            'title' => $request->title,
            'start_price' => $request->start_price,
            'price' => $request->price,
            'category_id' => $request->category_id,
            'user_id' => Auth::user()->id,
            'slug' => $slug,
            'description' => $request->description,
            'short_description' => $request->short_description,
            'auction_time' => $request->auction_time,
            'image' => $imageName,
        ]);

        $product->category;
        $product->user;

        return response()->json([
            'success' => true,
            'product' => $product
        ]);
    }

}

app/Http/Controllers/Dashboard/SettingsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SettingsController extends Controller
{
    //
    public function index(){
        return view('dashboard.user.settings');
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    //
    public function index(){
        return view('dashboard.user.index');
    }

    public function destroy($id){
        $product = User::query()->where('id',$id)->first();

        $product->delete();

        return response()->json([
            'success' => true
        ]);
    }
}

resources/views/dashboard/admin/bidproduct.blade.php
@extends('layouts.dashboard')

@section('title')
    Bid Products
@endsection()

@section('content')
    <div class="col-lg-12">
        <div class="main-card mb-3 card">
            <div class="card-body"><h5 class="card-title">Bid History</h5>
                <table class="mb-0 table">
                    <thead>
                    <tr>
                        <th>Username </th>
                        <th>Product Title</th>
                        <th>Bid</th>
                        <th>Bid Time</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                            @foreach($product->bids as $item)
                        <tr>
                            <td>{{ $item->user->first_name }}</td>
                            <td>{{ $product->title }}</td>
                            <td>${{ $item->bid }}</td>
                            <td>{{ $item->created_at }}</td>
                        </tr>
                       @endforeach
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script')

@endpush

resources/views/dashboard/admin/category.blade.php
@extends('layouts.dashboard')

@section('title')
    Category
@endsection()

@section('content')
    <div class="col-lg-12">
        <div class="main-card mb-3 card">
            <div class="card-header justify-content-between">
                <h5 class="card-title">Category table</h5>

                <button type="button" class="btn mr-2 mb-2 btn-primary create-category-btn" data-toggle="modal"
                        data-target=".create-category">Create Category
                </button>

            @push('modal')
                <!-- Small modal -->
                    <div class="modal fade create-category" tabindex="-1" role="dialog"
                         aria-labelledby="mySmallModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <form action="{{ route('dashboard.save') }}" method="post">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">Create new category</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        @csrf
                                        <div class="position-relative form-group">
                                            <label for="exampleEmail" class="">Name</label>
                                            <input name="name" type="text" class="form-control"
                                                   placeholder="New category name" value="{{ old('name') }}">
                                            @error('name')
                                                <small class="form-text" style="color: red">{{ $message }}</small>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                        </button>
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- Modal -->
                @endpush
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
                <table class="mb-0 table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th> Name</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td class="td-{{ $category->id }}">{{ $category->name }}</td>
                            <td>
                                <button type="button" class="btn mr-2 mb-2 btn-primary" data-toggle="modal" data-target=".category-edit{{ $category->id }}">
                                    Edit
                                </button>
                                @push('modal')
                                    <div class="modal fade category-edit{{ $category->id }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <input name="name" type="text" class="form-control edit-input" placeholder="New category name" value="{{ $category->name }}">                                          </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary edit-category-btn" data-id="{{$category->id}}">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endpush
                            </td>
                            <td>
                                <button type="button" class="btn btn-danger delete-category-btn" data-id="{{  $category->id }}">Delete</button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('assets/js/sweetalert.min.js') }}"></script>
    <script>
        $(function () {
            @error('name')
                $('.create-category-btn').click();
            @enderror



            $('.delete-category-btn').click(function () {
                const id = $(this).data('id');
                const $this = $(this);
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: '/dashboard/category/delete/'+id,
                            type:'delete',
                            dataType:'json',
                            success:function (res) {
                                if(res.success){
                                    Swal.fire(
                                        'Deleted!',
                                        'Your file has been deleted.',
                                        'success'
                                    )
                                    $this.parents('tr').remove()
                                }
                            }
                        })
                    }
                })
            })
        })
    </script>
    <script>
        $('.edit-category-btn').click(function () {
            const id = $(this).data('id');
            const $this = $(this);
            const name = $(this).parents('.modal-content').find('input.edit-input').val();

            $.ajax({
                url: '/dashboard/category/update/'+id,
                type:'put',
                data:{
                    name:name
                },
                dataType:'json',
                success:function (result) {
                    if(result.success){
                        $this.siblings().click();
                        $('.td-'+id).html(name);
                    }
                }
            })
        })
    </script>
@endpush

resources/views/dashboard/admin/edit.blade.php
@extends('layouts.dashboard')

@section('title')
    Account Setting
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body"><h5 class="card-title">Controls Types</h5>
                    <form class="">


                        <div class="position-relative form-group"><label  class="">First Name</label><input
                                name="first_name" type="text"
                                class="form-control" value="{{ $user->first_name }}">
                        </div>
                        <div class="position-relative form-group"><label class="">Email</label><input
                                name="email"  type="email"
                                class="form-control" value="{{ $user->email }}">
                        </div>
                        <div class="position-relative form-group"><label  class="">Middle Name</label><input
                                name="middle_name"  type="text"
                                class="form-control" value="{{ $user->middle_name }}">
                        </div>
                        <div class="position-relative form-group"><label class="">Last name</label><input
                                name="last_name" id="examplePassword" type="text"
                                class="form-control" value="{{ $user->last_name }}">
                        </div>
                        <div class="position-relative form-group"><label class="">Phone</label><input
                                name="phone" id="examplePassword" type="text"
                                class="form-control" value="{{ $user->phone }}">
                        </div>
                        <div class="position-relative form-group"><label  class="">Password</label><input
                                name="password"  type="password"
                                class="form-control" >
                        </div>
                        <div class="position-relative form-group"><label  class=""> Click to download this file</label>
                            <a href="{{ asset('uploads/'.$user->file) }}" download>{{ $user->file }}</a>
                        </div>


                        <button class="mt-1 btn btn-primary">update</button>
                        <a href="{{ route('dashboard.user') }}" class="mt-1 btn btn-danger">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')

@endpush

resources/views/dashboard/admin/index.blade.php
@extends('layouts.dashboard')

@section('title')
    User
@endsection()

@section('content')
    <div class="col-lg-12">
        <div class="main-card mb-3 card">
            <div class="card-body"><h5 class="card-title">Simple table</h5>
                <table class="mb-0 table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Middle Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        @if(isAdmin(Auth::user()) || Auth::user()->role == 'user' )
                        <th>Edit</th>
                        <th>Delete</th>
                         @endif
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->first_name }}</td>
                        <td>{{ $user->last_name }}</td>
                        <td>{{ $user->middle_name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->phone }}</td>
                        @if(isAdmin(Auth::user()) || Auth::user()->role == 'user' )
                        <td>
                            <a href="{{ route('dashboard.edit', ['id'=>$user->id]) }}" class="btn btn-success">Edit</a>
                        </td>
                        <td>

                            <button type="button"  class="btn btn-danger delete-user-btn" data-id="{{ $user->id }}">Delete</button>

                        </td>
                        @endif
                    </tr>
                      @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('assets/js/sweetalert.min.js') }}"></script>
    <script>
        $(function () {
            $('.delete-user-btn').click(function () {
                const id = $(this).data('id');
                const $this = $(this);
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: '/user/delete/'+id,
                            type:'delete',
                            dataType:'json',
                            success:function (res) {
                                if(res.success){
                                    Swal.fire(
                                        'Deleted!',
                                        'Your file has been deleted.',
                                        'success'
                                    )
                                    $this.parents('tr').remove()
                                }
                            }
                        })
                    }
                })
            })
        })
    </script>
@endpush