routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/','IndexController@index');


Route::get('/register', 'RegisterController@index')->name('register.index');

Route::group([
    'prefix' => 'aboutus',
    'as' => 'aboutus.',
], function (){
    Route::get('/', 'AboutUsController@index')->name('index');

});

Route::group([
    'prefix' => 'contactus',
    'as' => 'contactus.',
], function (){
    Route::get('/', 'ContactUsController@index')->name('index');

});
Route::group([
    'prefix' => 'product',
    'as' => 'product.',
], function (){
    Route::get('/{slug}', 'ProductController@index')->name('index');
    Route::post('/store', 'ProductController@store')->name('store');


});
//User dashboard
Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'Dashboard'
], function (){
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::delete('/delete/{id}', 'UserController@destroy')->name('destroy');
});

//Admin dashboard
Route::group([
    'prefix' => 'dashboard',
    'as' => 'dashboard.',
    'namespace' => 'Dashboard'
], function (){
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('/user', 'AdminController@user')->name('user');
    Route::get('/user/edit/{id}', 'AdminController@edit')->name('edit');
    Route::get('/product', 'ProductController@index')->name('product');
    Route::post('/product/store', 'ProductController@store')->name('product.store');
    Route::delete('/product/delete/{id}', 'ProductController@destroy')->name('product.destroy');


    Route::get('/category', 'CategoryController@index')->name('category');
    Route::post('/category/save', 'CategoryController@save')->name('save');
    Route::delete('/category/delete/{id}', 'CategoryController@destroy')->name('category.destroy');
    Route::put('/category/update/{id}', 'CategoryController@update')->name('category.update');


    Route::get('/bidproduct', 'BidProductController@index')->name('bid');





});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/dashboard.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Analytics Dashboard - This is an example dashboard created using build-in elements and components.</title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"/>
    <meta name="description" content="This is an example dashboard created using build-in elements and components.">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
    @yield('link')

</head>
<body>
<div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
    <div class="app-header header-shadow">
        <div class="app-header__logo">
            <div class="logo-src"></div>
            <div class="header__pane ml-auto">
                <div>
                    <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                            data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
        </div>
        <div class="app-header__mobile-menu">
            <div>
                <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                </button>
            </div>
        </div>
        <div class="app-header__menu">
                <span>
                    <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
        </div>
        <div class="app-header__content">
            <div class="app-header-left">
                <div class="search-wrapper">
                    <div class="input-holder">
                        <input type="text" class="search-input" placeholder="Type to search">
                        <button class="search-icon"><span></span></button>
                    </div>
                    <button class="close"></button>
                </div>
                <ul class="header-menu nav">
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            <i class="nav-link-icon fa fa-database"> </i>
                            Statistics
                        </a>
                    </li>
                    <li class="btn-group nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            <i class="nav-link-icon fa fa-edit"></i>
                            Product
                        </a>
                    </li>
                    <li class="dropdown nav-item">
                        <a href="{{ route('user.settings') }}" class="nav-link">
                            <i class="nav-link-icon fa fa-cog"></i>
                            Settings
                        </a>
                    </li>
                </ul>
            </div>
            <div class="app-header-right">
                <div class="header-btn-lg pr-0">
                    <div class="widget-content p-0">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left">
                                <div class="btn-group">
                                    <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                       class="p-0 btn">
                                        <span> {{ Auth::user()->first_name }} {{ Auth::user()->last_name }}</span>
                                        <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                    </a>
                                    <div tabindex="-1" role="menu" aria-hidden="true"
                                         class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="{{ route('logout') }}"
                                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                            </a>

                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                @csrf
                                            </form>

                                    </div>
                                </div>
                            </div>
                            <div class="widget-content-left  ml-3 header-user-info">
                                <div class="widget-heading">

                                </div>

                            </div>
                            <div class="widget-content-right header-user-info ml-3">
                                <button type="button" class="btn-shadow p-1 btn btn-primary btn-sm show-toastr-example">
                                    <i class="fa text-white fa-calendar pr-1 pl-1"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="app-main">
        <div class="app-sidebar sidebar-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                data-class="closed-sidebar">
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                        <span>
                            <button type="button"
                                    class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                                <span class="btn-icon-wrapper">
                                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                                </span>
                            </button>
                        </span>
            </div>
            <div class="scrollbar-sidebar">
                <div class="app-sidebar__inner">
                    <ul class="vertical-nav-menu">
                        <li class="app-sidebar__heading">Dashboards</li>

                            <li>
                                <a href="@if(!isAdmin(Auth::user())){{route('user.index')}}@else{{route('dashboard.index')}}@endif" @if(Route::currentRouteName() == 'user.index' || Route::currentRouteName() == 'dashboard.index') class="mm-active" @endif >
                                    <i class="metismenu-icon pe-7s-rocket"></i>
                                    Dashboard
                                </a>
                            </li>

                        @if(!isAdmin(Auth::user()))
                            <li>
                                <a href="{{ route('user.settings') }}" @if(Route::currentRouteName() == 'user.settings') class="mm-active" @endif >
                                    <i class="metismenu-icon pe-7s-settings"></i>
                                    Settings
                                </a>
                            </li>
                        @endif
                        @if(isAdmin(Auth::user()) || Auth::user()->role =='admin')
                            <li>
                                <a href="{{ route('dashboard.user') }}"  @if(Route::currentRouteName() == 'dashboard.user') class="mm-active" @endif>
                                    <i class="metismenu-icon pe-7s-box2"></i>
                                    User Profile
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('dashboard.category') }}" @if(Route::currentRouteName() == 'dashboard.category') class="mm-active" @endif>
                                    <i class="metismenu-icon pe-7s-box2"></i>
                                    Category
                                </a>
                            </li>

                        @endif
                        <li>
                            <a href="{{ route('dashboard.bid') }}" @if(Route::currentRouteName() == 'dashboard.bid') class="mm-active" @endif>
                                <i class="metismenu-icon pe-7s-box2"></i>
                                Bid Product
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('dashboard.product') }}" @if(Route::currentRouteName() == 'dashboard.product') class="mm-active" @endif>
                                <i class="metismenu-icon pe-7s-box2"></i>
                                Product
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="app-main__outer">
            <div class="app-main__inner">
                <div class="app-page-title">
                    <div class="page-title-wrapper">
                        <div class="page-title-heading">

                            <div>
                                @yield('title')
                            </div>
                        </div>
                    </div>
                </div>
                @yield('content')
            </div>
            <div class="app-wrapper-footer">
                <div class="app-footer">
                    <div class="app-footer__inner">
                        <div class="app-footer-left">
                            <ul class="nav">
                                <li class="nav-item">
                                    <a href="javascript:void(0);" class="nav-link">
                                        Footer Link 1
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:void(0);" class="nav-link">
                                        Footer Link 2
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="app-footer-right">
                            <ul class="nav">
                                <li class="nav-item">
                                    <a href="javascript:void(0);" class="nav-link">
                                        Footer Link 3
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:void(0);" class="nav-link">
                                        <div class="badge badge-success mr-1 ml-0">
                                            <small>NEW</small>
                                        </div>
                                        Footer Link 4
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    </div>
</div>
<script type="text/javascript" src="{{ asset('js/main.js') }}"></script>
<script src="{{ asset('assets/js/jquery-2.1.4.min.js') }}"></script>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>
@stack('modal')
@stack('script')
</body>
</html>